### ISSUE TITLE
 Category Nav spacing

### ISSUE THREAD

**Issue by dcashpeterson** [StfBauer/custom-learning-office-365#10]
There is some strangeness going on with the vertical nav styling. THe items jump around depending on when things are selected.

![image](https://github.com/StfBauer/custom-learning-office-365/assets/45491456/7104c097-9807-49cf-923d-c8d5dc3199e0)
![image](https://github.com/StfBauer/custom-learning-office-365/assets/45491456/fa63bdd6-4bfd-45fc-ba80-df4ed20e562e)
![image](https://github.com/StfBauer/custom-learning-office-365/assets/45491456/1170e3ea-6de2-42a8-9445-63efbe944fe4)

**Comment by StfBauer** [comment]
fixed
