### ISSUE TITLE
Search Results template for Assets 

### ISSUE THREAD

**Issue by dcashpeterson** [StfBauer/custom-learning-office-365#2]
In the search results when you search for SharePoint and select Assets from the Pivot the rule under the item doesn't go across the screen like it does for playlists. It happens when the description is empty or when it is short. Most assets don't have descriptions.
![image](https://github.com/StfBauer/custom-learning-office-365/assets/45491456/7727853c-f445-4df2-b674-bfb886e22af7)

**Comment by StfBauer** [comment]
fixed
