### ISSUE TITLE
Edit mode for custom sort cards not rendering propertly 

### ISSUE THREAD

**Issue by juliemturner** [StfBauer/custom-learning-office-365#4]
When the web part is pinned to a category and custom sort is enabled (must be more than 1 asset in the pinned category for this to happen), the custom sort icons are missing and the cards aren't the right size.

![image](https://github.com/StfBauer/custom-learning-office-365/assets/7570936/0411d489-4ee4-4bc8-a3a1-b13a26c33f71)

**Comment by dcashpeterson** [comment]
The card sizing is fixed but the dragging icon is very small and not aligned. 

![image](https://github.com/StfBauer/custom-learning-office-365/assets/45491456/453ce5a6-7b15-4cb8-a971-234eedd262bd)
