### ISSUE TITLE
 Styling for Admin Dialogs

### ISSUE THREAD

**Issue by dcashpeterson** [StfBauer/custom-learning-office-365#7]
We need updated styling for the dialogs in the Admin webpart for.

- About
- Add Content Pack
- Edit Content Pack

![image](https://github.com/StfBauer/custom-learning-office-365/assets/45491456/9cf1b84c-3dec-426c-83df-7babf5a57816)
![image](https://github.com/StfBauer/custom-learning-office-365/assets/45491456/08b916cb-458d-4912-a537-2e6e5684e212)

**Comment by StfBauer** [comment]
Fixed
